# pyproject.toml

[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxns"
version = "3.0.0"
description = "Nested Sampling in JAX"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{ name = "Joshua G. Albert", email = "albert@strw.leidenuniv.nl" }]
keywords = ["bayesian-methods", "scientific-computing", "probabilistic-programming", "nested-sampling", "model-comparison", "bayesian-computing", "jax", "scientific-machine-learning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
urls = { "Homepage" = "https://github.com/joshuaalbert/jaxns" }
dependencies = [
    "jax>=0.6.0",
    "jaxctx>=1.1.5",
    "matplotlib",
    "numpy",
    "scipy",
    "tfp-nightly",
]

[project.optional-dependencies]
examples = [
    "scikit-learn",
    "optax",
]
tests = [
    "scikit-learn",
    "networkx",
    "psutil",
    "pytest",
    "flake8",
    "ruff",
    "tomli; python_version < '3.11'",
]

[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["src"]
