"""Run the README quick start and optionally regenerate its static outputs."""

import argparse
import tempfile
from pathlib import Path

import jax
import matplotlib
import numpy as np
from jax import numpy as jnp
from jaxctx.priors.prior import Prior
from tensorflow_probability.substrates import jax as tfp

from jaxns.core import NestedSampler
from jaxns.model import Model
from jaxns.results import NestedSamplerResults

matplotlib.use("Agg")
tfpd = tfp.distributions

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
ASSET_DIRECTORY = REPOSITORY_ROOT / "docs" / "_static" / "readme_quick_start"
PREDICTOR = jnp.linspace(0.0, 1.0, 6)
OBSERVATIONS = jnp.asarray([0.15, 0.32, 0.83, 1.08, 1.52, 1.77])
MEASUREMENT_UNCERTAINTY = jnp.asarray(0.15)


def prior_model(predictor, observations, measurement_uncertainty):
    """Return the log likelihood for the README's straight-line model."""
    intercept = Prior(
        tfpd.Normal(loc=0.0, scale=1.0),
        name="intercept",
    ).realise()
    slope = Prior(
        tfpd.Normal(loc=0.0, scale=2.0),
        name="slope",
    ).realise()
    prediction = intercept + slope * predictor
    return jnp.sum(
        tfpd.Normal(
            loc=prediction,
            scale=measurement_uncertainty,
        ).log_prob(observations)
    )


def run_quick_start() -> NestedSamplerResults:
    """Run the exact model and sampler configuration shown in the README."""
    model = Model(prior_model=prior_model)
    args = (
        PREDICTOR,
        OBSERVATIONS,
        MEASUREMENT_UNCERTAINTY,
    )
    model.sanity_check(
        key=jax.random.PRNGKey(1),
        args=args,
    )

    sampler = NestedSampler(
        model=model,
        args=args,
        collect_phantom_samples=True,
    )
    state = sampler.run(key=jax.random.PRNGKey(6))
    jax.block_until_ready(state)
    return state.to_result().trim()


def exact_log_evidence() -> float:
    """Evaluate the linear-Gaussian model's analytic log-evidence."""
    predictor = np.asarray(PREDICTOR)
    observations = np.asarray(OBSERVATIONS)
    design = np.stack([np.ones_like(predictor), predictor], axis=1)
    prior_covariance = np.diag([1.0, 4.0])
    noise_covariance = np.multiply(
        float(MEASUREMENT_UNCERTAINTY) ** 2,
        np.eye(observations.size),
    )
    marginal_model_covariance = design @ prior_covariance @ design.T
    covariance = noise_covariance + marginal_model_covariance
    covariance_sign, covariance_log_determinant = np.linalg.slogdet(
        covariance
    )
    if covariance_sign <= 0:
        raise ValueError(
            "The analytic observation covariance must be positive."
        )
    normalisation = observations.size * np.log(2.0 * np.pi)
    mahalanobis = observations @ np.linalg.solve(
        covariance,
        observations,
    )
    negative_log_density = (
        normalisation + covariance_log_determinant + mahalanobis
    )
    return float(-0.5 * negative_log_density)


def write_outputs(
        results: NestedSamplerResults,
        output_directory: Path,
) -> str:
    """Write and validate the summary and plots generated by the demo."""
    output_directory.mkdir(parents=True, exist_ok=True)
    summary_file = output_directory / "summary.txt"
    diagnostics_file = output_directory / "diagnostics.png"
    cornerplot_file = output_directory / "cornerplot.png"
    evidence_file = output_directory / "evidence.png"

    results.summary(f_obj=summary_file)
    results.plot_diagnostics(save_file=diagnostics_file)
    results.plot_cornerplot(
        variables=["intercept", "slope"],
        save_name=cornerplot_file,
    )
    results.plot_evidence(
        num_samples=4096,
        conditionings=("classic", "phantom"),
        key=jax.random.PRNGKey(3),
        exact_log_Z=exact_log_evidence(),
        save_name=evidence_file,
    )

    summary = summary_file.read_text(encoding="utf-8")
    variables = {name for name, _ in results.X_samples.iter_items()}
    assert variables == {"intercept", "slope"}
    assert np.isfinite(float(results.log_Z_mean))
    assert int(results.total_num_samples) > 0
    assert "intercept: mean +- std.dev." in summary
    assert "slope: mean +- std.dev." in summary
    assert diagnostics_file.stat().st_size > 0
    assert cornerplot_file.stat().st_size > 0
    assert evidence_file.stat().st_size > 0
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write-assets",
        action="store_true",
        help="Write the maintained README assets into docs/_static.",
    )
    arguments = parser.parse_args()
    results = run_quick_start()

    if arguments.write_assets:
        print(write_outputs(results, ASSET_DIRECTORY))
        return

    # CI verifies the complete public workflow without dirtying the checkout.
    with tempfile.TemporaryDirectory(prefix="jaxns-readme-") as directory:
        print(write_outputs(results, Path(directory)))


if __name__ == "__main__":
    main()
