version: "3"
services:
  tests:
    image: jaxns:local
    container_name: jaxns
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    env_file:
      - local.env
    volumes:
      - /dev/shm:/dev/shm
